version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - angular-spa
      - angular-ssr
      - nestjs
      - express
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/modsecurity.conf:/etc/nginx/modsecurity.conf
      - ./nginx/ssl:/etc/nginx/ssl
    restart: always
    networks:
      - app-network

  angular-spa:
    build: ./angular-spa
    container_name: angular-spa
    networks:
      - app-network

  angular-ssr:
    build: ./angular-ssr
    container_name: angular-ssr
    ports:
      - "4000:4000"
    networks:
      - app-network

  nestjs:
    build: ./nestjs
    container_name: nestjs-api
    ports:
      - "3001:3000"
    networks:
      - app-network

  express:
    build: ./express
    container_name: express-api
    ports:
      - "3002:3000"
    networks:
      - app-network

  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
    networks:
      - app-network
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

networks:
  app-network:

volumes:
  oracle-data:
